name: Busted
on: [push, pull_request]
jobs:
  sile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run Busted
        uses: lunarmodules/busted@v2
        with: 
          args: --run=ciUnit
