
name: Convert CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Neovim
      run: |
        sudo apt-get update
        sudo apt-get install -y neovim

    - name: Set up lua
      uses: leafo/gh-actions-lua@v9

    - name: Set up LuaRocks
      uses: leafo/gh-actions-luarocks@v4

    - name: Install dependencies
      run: 
        luarocks install vusted
        git clone https://github.com/notomo/vusted.git

    - name: Run tests
      run: |
        vusted tests/
